#ifndef slic3r_OrcaExt_InstanceContact_hpp_
#define slic3r_OrcaExt_InstanceContact_hpp_

// [ORCAPORT FILE] OrcaExt InstanceContact - PerObject Support (SU-1): cross-object support
// avoidance. Builds, per object layer, the footprint of every OTHER PrintObject's instances
// (body plus already-generated support) in this object's local frame, for injection into the
// support collision volumes. Read-only; requires lslices of all objects (posSlice done).
// Source: NEOTKOCM_RELEASE_2_39.md; fork sha c3508e5a92.

#include <vector>

#include "Polygon.hpp"

namespace Slic3r {
class PrintObject;
class SupportLayer;

namespace OrcaExt {

// Per-layer occupancy of the other objects' instances, indexed by this object's layer number and
// expressed in this object's local frame. Empty when the feature is inactive (toggle off,
// by-object print, or no neighbour within range) so callers can no-op at zero cost.
//
// [ORCAPORT:PF-10-multisupport] This also returns the supports generated by earlier passes of the SAME
// object (PrintObject::support_pass_obstacles()), so the multi-pass dispatcher keeps each pass out
// of the supports another pass already built, independently of the PerObject Support toggle.
std::vector<Polygons> neighbor_occupancy(const PrintObject &object);

// [ORCAPORT:PF-10-multisupport] Per object-layer footprint of the given already-generated support layers,
// in this object's local frame. Used by the multi-pass dispatcher to publish earlier passes'
// supports as obstacles via PrintObject::set_support_pass_obstacles().
std::vector<Polygons> support_layers_occupancy(const PrintObject &object,
                                               const std::vector<SupportLayer *> &layers);

// True when cross-object support avoidance is effectively active for this object: the per-object
// toggle is on AND the plate prints by layer (in by-object mode the neighbours may not exist yet,
// so the avoidance is inert). Single source of truth for every place that reacts to the feature.
bool cross_object_active(const PrintObject &object);

} // namespace OrcaExt
} // namespace Slic3r

#endif
